// TTC PHC Calendar — live data feed. REWRITTEN by the daily phc-scan run; do not hand-edit.
window.PHC_DATA = {
  as_of: "2026-07-21 (daily scheduled run)",
  gdd: {
    value: 1427.5, rate14: 30.1, base: 50, from: "2026-03-01", location: "Logan UT",
    next: [
      { label: "Pine needle scale gen-2 crawlers — OPEN (1388–1917)", gdd: 1388, date: "2026-07-20" },
      { label: "Oystershell scale gen-2 crawlers OPEN", gdd: 1600, date: "2026-07-26" },
      { label: "Pine needle scale gen-2 CLOSES", gdd: 1917, date: "2026-08-06" },
      { label: "Spruce spider mite fall round OPENS", gdd: 2375, date: "2026-08-21" }
    ]
  },
  worklist: [
    { s: "PAST", job: 7719, client: "Greg Batty", line: "Mectinite micro — lilac/ash borer (green ash)", why: "Window closed ~early Jul (GDD 148–299; now 1428). Verdur ×2 parked 9/25 ✓; Cambistat open. 7/16 visit ran — verify what it covered.", action: "DAVID: late-treat, roll to spring 2027, or adjust", amt: 361 },
    { s: "PAST", job: 5904, client: "Jason Allen", line: "FerriPlus soil inj — 'spring 2025'", why: "Two springs missed; parked visit 4/15/25 never ran (park-date lie); job LATE. Brain allows reduced-dose salvage to ~Aug.", action: "DAVID: reduced-dose now or rebid 2027", amt: 224 },
    { s: "PAST", job: 7385, client: "Kelly Wiggington", line: "Myclotect foliar — 'best in spring'", why: "Spring window passed; line priced $0. Visits 4/9 + 4/24 DID run — price + close, or decide remainder.", action: "DAVID: decide + price", amt: 0 },
    { s: "PAST", job: 6807, client: "Heather Larsen", line: "Fruit insecticides Jul–Aug 2025", why: "The 2025 season is gone (both 2025 visits ran); job still action_required.", action: "OFFICE: close or renew as 2026", amt: 200 },
    { s: "PAST", job: 7761, client: "Janice Gladwell", line: "Myclotect — lilac powdery mildew (preventive)", why: "Preventive window = bud break → leaves formed. Aphid + iron lines below still live.", action: "DAVID: skip this year?", amt: 60 },
    { s: "PAST", job: 7731, client: "Debbie Hancey", line: "Mectinite micro — lilac/ash borer (green ash 8.5in)", why: "SOLD 7/2 — after the borer window closed (GDD 148–299; now 1428). The Batty pattern. Iron + Cambistat + foliar handled on the CLOSING row.", action: "DAVID: treat late, spring 2027, or adjust", amt: 161.5 },
    { s: "CLOSING", job: 6870, client: "Aurora & Geo Villa", line: "Mectinite — ponderosa bark beetles", why: "Unscheduled 344 DAYS; client called 7/15 asking if mid-July is too late. Window = OPEN GAP #1.", action: "DAVID: answer + schedule or refund", amt: 323 },
    { s: "CLOSING", job: 7717, client: "Spaulding (Providence)", line: "FerriPlus soil inj — 'apply ASAP (already slightly late)'", why: "Visit is TODAY 7/21 8 AM — iron rides it.", action: "ERYN: confirm today's visit ran + covered the iron", amt: 0 },
    { s: "CLOSING", job: 7771, client: "Rial Chew", line: "FerriPlus — 9 chlorotic trees", why: "Iron after mid-June = already-late/ASAP (Brain); salvage runs to ~Aug. Pair with deep-watering.", action: "ERYN: schedule ≤2 wks", amt: 697.5 },
    { s: "CLOSING", job: 7779, client: "Sher Lisonbee", line: "Chelated iron — hawthorn", why: "Iron ASAP rule; also check sprinkler/vinca watering note. (Sibling 7778 is pruning-only — no PHC.)", action: "ERYN: schedule ≤2 wks", amt: 90 },
    { s: "CLOSING", job: 7761, client: "Janice Gladwell", line: "FerriPlus — hedge maple + magnolia (+ Tengard aphids NOW)", why: "Iron ASAP rule; aphid spray is scout-open. One visit, both lines.", action: "ERYN: one visit, both lines", amt: 185 },
    { s: "CLOSING", job: 7785, client: "Karen Higley (Preston)", line: "FerriPlus ×7 maples + soil analysis", why: "Iron ASAP rule (PHC in Idaho is fine — no dig). Samples collected 7/13 — lab work in flight.", action: "ERYN: schedule ≤2 wks", amt: 288.5 },
    { s: "CLOSING", job: 7786, client: "Nancy Sassano", line: "FerriPlus+Mn ×4 maples (+ Cambistat OPEN)", why: "Iron ASAP rule; PGR rides the same visit.", action: "ERYN: schedule ≤2 wks", amt: 407 },
    { s: "CLOSING", job: 7731, client: "Debbie Hancey", line: "FerriPlus (Autumn Blaze) + Cambistat + mildew/aphid foliar", why: "Iron ASAP rule; Cambistat open; mildew preventive past but aphid half scout-OK. Second visit still unscheduled.", action: "ERYN: schedule ≤2 wks", amt: 243 },
    { s: "CLOSING", job: 7417, client: "Kami Antriyao", line: "Transtect soil inj — cottony maple scale ('best in spring') + Cambistat (open)", why: "Spring passed; systemic timing = DAVID call. UNSCHEDULED 117 DAYS (created 3/26) — age flag.", action: "DAVID: treat now or spring?", amt: 612 },
    { s: "CLOSING", job: 7758, client: "Steffanie Norton", line: "Soil inj ×2 (iron, 'apply ASAP') + Cambistat ×2", why: "Iron ASAP rule; PGR lines open (Mar–Nov) — one visit does all four.", action: "ERYN: schedule ≤2 wks", amt: 379.75 },
    { s: "CLOSING", job: 7755, client: "Jason Holladay", line: "FerriPlus soil inj — crabapple + aspen", why: "Iron ASAP rule (line says ANNUAL, every spring/early summer).", action: "ERYN: schedule ≤2 wks", amt: 195 },
    { s: "CLOSING", job: 7737, client: "Melanie Kvarfordt", line: "Trimtect PGR — cotoneaster hedge", why: "Event window: within 1–2 wks of shearing. Shear ran 7/15 → spray by ~7/29 (≤8 days). Job LATE; stray 7/10 visit sits uncompleted.", action: "ERYN/TREVOR: spray THIS week + tidy the 7/10 visit", amt: 235 },
    { s: "CLOSING", job: 7730, client: "Tami Warnick", line: "Transtect — cottony maple scale + Honeycrisp one-off insect/fungus spray", why: "Transtect line's own window 'late Jun–early Jul' just past; Honeycrisp spray is this-season. 7/3 visit ran — verify coverage; second visit unscheduled.", action: "DAVID: Transtect now or spring? + verify 7/3 coverage", amt: 128 },
    { s: "GAP", job: 7788, client: "Shayla Snarr", line: "Mectinite — spruce IPS beetle ×8", why: "Ips window not in windows.md (gap #8) — abstained, not guessed.", action: "DAVID: give the window", amt: 760 },
    { s: "GAP", job: 7745, client: "Roger Cook", line: "Mectinite micro — HONEY LOCUST BORER ($351.50) + Cambistat ($185, open)", why: "Gap #3 verbatim — David: 'I'll have to remind myself the timing.' Cambistat could ride the same visit once the window is known.", action: "DAVID: give the window (gap #3)", amt: 536.5 },
    { s: "SOON", job: 7759, client: "Steffanie Norton", line: "Verdur macro ×2 — fall window", why: "Unscheduled but the window is fall (Sep 15–Oct 15) — park with the 9/25 batch.", action: "ERYN: park on the fall batch", amt: 392 },
    { s: "SOON", job: 7792, client: "Debbie Hancey", line: "Verdur macro — fall window", why: "Same — park with the 9/25 batch.", action: "ERYN: park on the fall batch", amt: 150 },
    { s: "OPEN", job: 7776, client: "Rich & Colleen Gordin", line: "Cambistat PGR ×3 Freeman maples", why: "Mar–Nov window. Visit runs TODAY 7/21 11 AM ✓. (Sibling 7775 is pruning-only — title lied, dropped from PHC.)", action: "none — confirm it ran", amt: 294 },
    { s: "OPEN", job: 7749, client: "Katie Brinck", line: "Cambistat PGR — 3 crabapples", why: "Mar–Nov window.", action: "ERYN: schedule anytime", amt: 255 },
    { s: "OPEN", job: 7760, client: "Anna Trappett", line: "Cambistat PGR — Crimson King", why: "Mar–Nov window.", action: "ERYN: schedule anytime", amt: 100 },
    { s: "ONTRACK", job: 7559, client: "Rob Levan", line: "Aphid spray 3/3", why: "Visits 6/19 ✓ 7/17 ✓ → 8/14.", action: "none", amt: 55 },
    { s: "ONTRACK", job: 7419, client: "Anna Trappett", line: "Leaf hopper foliar ×3", why: "6/29 ✓ → 7/27 → 8/7.", action: "none", amt: 270 },
    { s: "ONTRACK", job: 7454, client: "Danny Gomez", line: "Fruit program", why: "3 rounds done, next 7/23.", action: "none", amt: 475 },
    { s: "ONTRACK", job: 7466, client: "Joyce Caliendo", line: "Fruit program", why: "3 rounds done, next 7/23.", action: "none", amt: 45 },
    { s: "DORMANT", job: 7024, client: "Joyce Caliendo", line: "Verdur macro — fall", why: "Parked 9/25 ≈ window (Sep 15–Oct 15).", action: "none", amt: 152 },
    { s: "DORMANT", job: 7652, client: "Kelli King", line: "Verdur macro — fall", why: "Parked 9/25 ≈ window.", action: "none", amt: 260 },
    { s: "DORMANT", job: 7660, client: "Amy Billings", line: "Verdur macro — fall", why: "Parked 9/25 ≈ window.", action: "none", amt: 157.5 },
    { s: "DORMANT", job: 7676, client: "Miriam Rich", line: "Verdur macro ×2 — fall", why: "Parked 9/25 ≈ window.", action: "none", amt: 442.5 },
    { s: "DORMANT", job: 7722, client: "Eileen Clements", line: "Winter pruning (dormancy)", why: "Parked 12/1 ≈ window (Dec–Feb).", action: "none", amt: 375 },
    { s: "DORMANT", job: 7774, client: "Kylie Fullmer", line: "Winter structural prunes ×16", why: "Parked 12/1 ≈ window.", action: "none", amt: 160 },
    { s: "DORMANT", job: 7793, client: "Debbie Hancey", line: "Crimson King fungicide series — spring 2027 pre-create", why: "Next-spring regimen (bud break → leaves formed, 3–4 sprays). Visit not yet parked.", action: "ERYN: park on the spring-2027 batch", amt: 200 },
    { s: "DORMANT", job: 7729, client: "Flora Shrode", line: "Myclotect anthracnose series — spring 2027", why: "Parked 3/26/27 ≈ window (leaf expansion) ✓.", action: "none", amt: 200 },
    { s: "DORMANT", job: 7730, client: "Tami Warnick", line: "2027 pre-creates: mildew preventive series ($165) + Fruit Spraying Plus ($375)", why: "Both lines say 'if approved, 2027' — parked correctly under the open job.", action: "none", amt: 540 },
    { s: "DORMANT", job: 7504, client: "Maxine Karren", line: "Florel — chokecherry fruit elimination, spring 2027", why: "Parked 4/16/27 at flowering per the line. NOTE: Florel windows.md row still open (gap #9).", action: "none", amt: 80 },
    { s: "TRIAGE", job: 0, client: "Fruit-spray fleet (12 jobs)", line: "action_required, all rounds complete", why: "Final visits ran 7/16–7/17 — the 2026 rounds are done; jobs sitting action_required (+3 already in requires_invoicing: 7442/7472/7591). Status hygiene, not biology. (7432/7439/7444 titles still say '2025' — stale titles, work is current.)", action: "ERYN: sweep to invoicing/close", amt: 0 },
    { s: "TRIAGE", job: 7465, client: "Carlo Lemon", line: "Fruit-Complete program (spring 2026)", why: "VERIFIED today: all 7 visits completed (last 7/16) — nothing left to run.", action: "ERYN: invoice/close", amt: 475 },
    { s: "TRIAGE", job: 6798, client: "Sue Baker", line: "Tree watering, summer 2025", why: "Stale-season: 2025 job still action_required (visit 8/14/25 long past). Not a PHC treatment — hygiene only.", action: "ERYN: close or renew as 2026", amt: 75 }
  ],
  gaps: [
    "#1 Mectinite/bark-beetle on ponderosa — mid-July too late? (LIVE: #6870, client waiting since 7/15 — 344 days unscheduled)",
    "#2 Miticide actual month/window",
    "#3 Honey locust borer window — LIVE on #7745 Cook ($536.50 waiting)",
    "#4 Lilac/ash borer dates — confirm (hedged)",
    "#5 Cottony maple scale crawler window — AND the Transtect systemic timing (LIVE on #7417 + #7730)",
    "#6 Powdery mildew — one or two applications?",
    "#7 Which line items fall under the Mar–Nov PGR window",
    "#8 Spruce ips treatment window (#7788 Snarr)",
    "#9 Florel (fruit elimination) window — no windows.md row (#7504 parked 4/16/27, looks right, confirm via office-log)"
  ]
};
